---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-jenkins-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-jenkins-deployer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-jenkins-deployer-role
subjects:
- kind: ServiceAccount
  name: knative-jenkins-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-jenkins-deployer-role
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - '*'